[2024-06-21T05:47:01.302+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T05:47:01.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_snowflake.transform_dm_supplier_revenue scheduled__2024-06-19T00:00:00+00:00 [queued]>
[2024-06-21T05:47:01.584+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_snowflake.transform_dm_supplier_revenue scheduled__2024-06-19T00:00:00+00:00 [queued]>
[2024-06-21T05:47:01.586+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T05:47:01.871+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_dm_supplier_revenue> on 2024-06-19 00:00:00+00:00
[2024-06-21T05:47:01.907+0000] {standard_task_runner.py:63} INFO - Started process 48 to run task
[2024-06-21T05:47:02.077+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', '***_to_snowflake', 'transform_dm_supplier_revenue', 'scheduled__2024-06-19T00:00:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_dag.py', '--cfg-path', '/tmp/tmpwqe6yyz1']
[2024-06-21T05:47:02.094+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask transform_dm_supplier_revenue
[2024-06-21T05:47:02.693+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_to_snowflake.transform_dm_supplier_revenue scheduled__2024-06-19T00:00:00+00:00 [running]> on host fc0dc40dc1bb
[2024-06-21T05:47:03.693+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Query-Query Ninja' AIRFLOW_CTX_DAG_ID='***_to_snowflake' AIRFLOW_CTX_TASK_ID='transform_dm_supplier_revenue' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T00:00:00+00:00'
[2024-06-21T05:47:03.722+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T05:47:04.093+0000] {warnings.py:109} WARNING - /opt/airflow/etls/snowflake_etl.py:50: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, pg_engine)

[2024-06-21T05:47:04.103+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T05:47:04.105+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/etls/snowflake_etl.py", line 50, in transform_dm_supplier_revenue
    df = pd.read_sql_query(query, pg_engine)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 526, in read_sql_query
    return pandas_sql.read_query(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2738, in read_query
    cursor = self.execute(sql, params)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
AttributeError: 'Engine' object has no attribute 'cursor'
[2024-06-21T05:47:04.334+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=***_to_snowflake, task_id=transform_dm_supplier_revenue, run_id=scheduled__2024-06-19T00:00:00+00:00, execution_date=20240619T000000, start_date=20240621T054701, end_date=20240621T054704
[2024-06-21T05:47:04.457+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task transform_dm_supplier_revenue ('Engine' object has no attribute 'cursor'; 48)
[2024-06-21T05:47:04.596+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-21T05:47:04.854+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-21T05:47:04.947+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
